---
  - name: Show Current Password
    hosts: Aruba
    connection: network_cli
    gather_facts: no

    tasks:

      - name: Disabling Encryption
        aruba_config:
          commands: ['configure terminal',
            'encrypt disable',
            'end']

      - name: Show Current Password
        aruba_command:
          commands:
            - 'show wlan ssid-profile guest | include Passphrase'

        register: Cleartext_Password

      - name: Current Password is
        debug:
          var: Cleartext_Password['stdout']


      - lineinfile:
          path: ./outputs/Cleartext_Password.txt
          line: "{{ {inventory_hostname: Cleartext_Password['stdout']} | string }}"
          create: yes
 