---
  - name: CISCO SHOW COMMANDS
    hosts: Cisco
    connection: network_cli
    gather_facts: no

    tasks:

      - name: SHOW IP INTERFACE BRIEF
        ios_command:
          commands:
            - "show ip int brief | ex un"
        register: output

      - name: Gather output
        debug:
          var: output['stdout']